# Generated by Django 3.0.7 on 2020-06-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
